version: '3'

services:
    js_server:
        image: node:latest
        working_dir: /l1_json
        volumes:
        - ./js_files:/l1_json
        command: bash npm_run.sh
        expose: 
        - 8001

    lite_server:
        image: node:latest
        working_dir: /l1_lite
        volumes:
        - ./lite_files:/l1_lite
        command: bash npm_run.sh
        expose:
        - 3000
        
    nginx:
        image: nginx
        volumes:
        - ./templates:/etc/nginx/templates
        ports:
        - "8800:80"
        environment:
        - NGINX_HOST=0.0.0.0
        - NGINX_PORT=80
        links: 
        - js_server
        - lite_server
       
